# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/ki18n': '@latest'
    'plasma/libplasma': '@latest'

Options:
  require-passing-tests-on: [ '@all' ]
